name: Build Docker Images

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        # roscore
        docker build Dockerfiles/roscore --tag roscore:$(date +%s)
        # mavros
        docker build Dockerfiles/mavros/melodic --tag mavros:melodic-ros-base
